# Generated by Django 5.1 on 2024-09-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(help_text='Must be filled in.', max_length=20)),
                ('store_adress', models.TextField()),
                ('store_region', models.CharField(help_text='Where', max_length=15)),
                ('chain_id', models.ForeignKey(help_text='Id off the super chain.', on_delete=django.db.models.deletion.CASCADE, to='market.supermarketchain')),
            ],
        ),
    ]
