# Generated by Django 5.1 on 2024-09-01 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=25)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('unit_type', models.CharField(max_length=10)),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_sale', models.BooleanField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.store')),
            ],
        ),
    ]
