# Generated by Django 5.1 on 2024-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_user_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
