# Generated by Django 5.1 on 2024-09-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_user_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorePreferance',
            fields=[
                ('USP_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.user')),
            ],
        ),
    ]
