# Generated by Django 5.1 on 2024-09-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_userstorepreferance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userstorepreferance',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userstorepreferance',
            name='store_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_adress',
            new_name='store_address',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='chain_id',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='market.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='market.supermarketchain'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(help_text='Must be filled in.', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_region',
            field=models.CharField(help_text='Where in NZ', max_length=50),
        ),
        migrations.AlterField(
            model_name='supermarketchain',
            name='chain_name',
            field=models.CharField(choices=[('Nw', 'New World'), ('Cd', 'Countdown'), ('Ps', 'Pak n Save'), ('Fc', 'Fresh Choice')], default='Cd', max_length=2),
        ),
        migrations.CreateModel(
            name='UserStorePreference',
            fields=[
                ('usp_id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by', to='market.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='market.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserStorePreferance',
        ),
    ]
